set(CTEST_BUILD_CONFIGURATION "Release")
SET(ENV{CC} /usr/bin/gcc)
SET(ENV{CXX} /usr/bin/g++44)
set(COMPILER_NAME "GCC")
set(COMPILER_VERSION "4.4.7")

set(WITH_MEMCHECK FALSE)
set(WITH_COVERAGE FALSE)
