set(CTEST_BUILD_CONFIGURATION "Debug")
SET(ENV{CC} /usr/bin/clang)
SET(ENV{CXX} /usr/bin/clang++)
set(COMPILER_NAME "Clang")
set(COMPILER_VERSION "3.4-1ubuntu3")

set(WITH_MEMCHECK FALSE)
set(WITH_COVERAGE FALSE)
