set(CTEST_CMAKE_GENERATOR "Visual Studio 8 2005")

set(CTEST_BUILD_CONFIGURATION "Release")
set(COMPILER_NAME "Visual Studio")
set(COMPILER_VERSION "8.2005")

set(WITH_MEMCHECK FALSE)
set(WITH_COVERAGE FALSE)
