set(CTEST_CMAKE_GENERATOR "Visual Studio 10")

set(CTEST_BUILD_CONFIGURATION "Debug")
set(COMPILER_NAME "Visual Studio")
set(COMPILER_VERSION "10.2010")

set(WITH_MEMCHECK FALSE)
set(WITH_COVERAGE FALSE)
